name: Create release candidate

on:
  workflow_call:

jobs:
  create-rc:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          # The release bot must push the commits to satisfy the branch protection rules.
          token: ${{ secrets.RELEASE_APPROVER }}
          persist-credentials: true

      - name: Create pre-release tag
        run: |
          echo "Increasing pre-release counter.."
          RELEASE_COUNTER=$( cat .pre_release.counter )
          RELEASE_COUNTER=$((RELEASE_COUNTER+1))
          echo -n $RELEASE_COUNTER > .pre_release.counter
          RELEASE_VERSION=$( echo ${{ github.ref_name }} | cut -d "-" -f 1 )
          RC_TAG=${RELEASE_VERSION}-rc${RELEASE_COUNTER}
          echo Release candidate tag: ${RC_TAG}
          echo "RC_TAG=${RC_TAG}" >> $GITHUB_ENV

      - name: Update pre-release counter and create rc git tag
        id: commit
        run: |
          git config user.name ${{ github.actor	}}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git add .pre_release.counter
          git commit -m "Update pre-release counter for RC ${{ env.RC_TAG }}"
          git push
          git tag ${{ env.RC_TAG }}
          git push origin ${{ env.RC_TAG }}

      - name: Write success summary
        run: |
          echo "================================
                Release candidate **${{ env.RC_TAG }}** created successfully.
                Please validate the release candidate before proceeding.

                1) If issues **are** found:
                  * Open PRs against the **${{ github.ref_name }}** branch to address the issues
                  * Trigger the [Create Release Candidate](${{ github.server_url }}/${{ github.repository }}/actions/workflows/create-release-candidate.yml) workflow again
                    **_Note:_** Run the workflow from branch **${{ github.ref_name }}**
                  * Perform the same actions as (2)
                2) Once ready to release:
                  * Trigger the [Create Release PR](${{ github.server_url }}/${{ github.repository }}/actions/workflows/create-release-pr.yml) workflow
                    **_Note:_** Run the workflow from tag **${{ env.RC_TAG }}** or from branch **${{ github.ref_name }}**

                ==================================" | sed 's/^[[:space:]]*//g' >> $GITHUB_STEP_SUMMARY

      - name: Write failure summary
        if: failure()
        run: |
          echo "==================================
                ERROR: Failed to create release candidate.
                Check action output and/or contact @project-llzk/maintainers team for clarifications.

                ==================================" | sed 's/^[[:space:]]*//g' >> $GITHUB_STEP_SUMMARY
